# Generated by Django 5.1.4 on 2025-01-02 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_ref_num', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('user_fname', models.CharField(max_length=50)),
                ('user_lname', models.CharField(max_length=50)),
                ('user_mname', models.CharField(max_length=50, null=True)),
                ('user_suff', models.CharField(max_length=25, null=True)),
                ('user_email', models.EmailField(max_length=100, null=True)),
                ('user_contact_num', models.CharField(max_length=20, null=True)),
                ('user_birthdate', models.DateField()),
                ('user_sex', models.CharField(max_length=25)),
                ('user_address', models.CharField(max_length=255)),
                ('user_guardian', models.CharField(max_length=100)),
                ('user_parent', models.CharField(max_length=100)),
                ('user_work_status', models.CharField(max_length=25)),
            ],
        ),
    ]
