# Generated by Django 5.1.4 on 2025-01-06 02:14

import django.utils.timezone
import user_profile.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(blank=True, default='', max_length=254, unique=True)),
                ('ref_num', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('mname', models.CharField(max_length=50, null=True)),
                ('suffix', models.CharField(max_length=25, null=True)),
                ('contact_num', models.CharField(max_length=20, null=True)),
                ('birthdate', models.DateField()),
                ('sex', models.CharField(max_length=25)),
                ('address', models.CharField(max_length=255)),
                ('guardian', models.CharField(max_length=100)),
                ('parent', models.CharField(max_length=100)),
                ('work_status', models.CharField(max_length=25)),
                ('is_active', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', user_profile.models.CustomUserManager()),
            ],
        ),
    ]
